export interface TenantSeed {
  id: string;           // e.g. "tenant-acme"
  name: string;         // e.g. "Acme Corp — GitHub ReBAC"
  description: string;
  tuples: { subject: string; relation: string; object: string }[];
}

export const TENANTS: TenantSeed[] = [
  {
    id: "tenant-acme",
    name: "Acme Corp — Software Engineering",
    description: "A software company with engineering and security teams across 4 repos",
    tuples: [
      // Org
      { subject: "user:alice", relation: "admin", object: "org:acme" },
      { subject: "user:bob", relation: "member", object: "org:acme" },
      { subject: "user:carol", relation: "member", object: "org:acme" },
      // Teams
      { subject: "user:alice", relation: "admin", object: "team:engineering" },
      { subject: "user:bob", relation: "member", object: "team:engineering" },
      { subject: "user:mallory", relation: "member", object: "team:engineering" },
      { subject: "user:carol", relation: "admin", object: "team:security" },
      // Repos via subject-sets
      { subject: "team:engineering#member", relation: "admin", object: "repo:api-gateway" },
      { subject: "team:engineering#member", relation: "maintainer", object: "repo:frontend" },
      { subject: "team:security#member", relation: "viewer", object: "repo:api-gateway" },
      { subject: "team:security#member", relation: "admin", object: "repo:vault" },
      // Deny
      { subject: "user:mallory", relation: "banned", object: "repo:vault" },
    ],
  },
  {
    id: "tenant-fintech",
    name: "FinPay — Payments Platform",
    description: "Fintech company with strict access tiers: compliance, engineering, ops",
    tuples: [
      { subject: "user:priya", relation: "admin", object: "org:finpay" },
      { subject: "user:rahul", relation: "member", object: "org:finpay" },
      { subject: "user:sara", relation: "member", object: "org:finpay" },
      { subject: "user:tom", relation: "member", object: "org:finpay" },
      { subject: "user:priya", relation: "admin", object: "team:compliance" },
      { subject: "user:rahul", relation: "admin", object: "team:payments-eng" },
      { subject: "user:sara", relation: "member", object: "team:payments-eng" },
      { subject: "user:tom", relation: "member", object: "team:ops" },
      { subject: "team:compliance#member", relation: "viewer", object: "repo:payment-core" },
      { subject: "team:payments-eng#member", relation: "admin", object: "repo:payment-core" },
      { subject: "team:payments-eng#member", relation: "maintainer", object: "repo:settlement-api" },
      { subject: "team:ops#member", relation: "viewer", object: "repo:settlement-api" },
      { subject: "user:tom", relation: "banned", object: "repo:payment-core" },
    ],
  },
  {
    id: "tenant-healthco",
    name: "HealthCo — Medical Records",
    description: "Healthcare org: doctors, nurses, and admins across patient data and pharmacy repos",
    tuples: [
      { subject: "user:dr-jones", relation: "admin", object: "org:healthco" },
      { subject: "user:nurse-amy", relation: "member", object: "org:healthco" },
      { subject: "user:admin-luis", relation: "admin", object: "org:healthco" },
      { subject: "user:intern-jay", relation: "member", object: "org:healthco" },
      { subject: "user:dr-jones", relation: "admin", object: "team:physicians" },
      { subject: "user:nurse-amy", relation: "member", object: "team:nursing" },
      { subject: "user:admin-luis", relation: "admin", object: "team:admin" },
      { subject: "team:physicians#member", relation: "admin", object: "repo:patient-records" },
      { subject: "team:nursing#member", relation: "viewer", object: "repo:patient-records" },
      { subject: "team:admin#member", relation: "maintainer", object: "repo:billing-system" },
      { subject: "team:physicians#member", relation: "maintainer", object: "repo:pharmacy" },
      { subject: "user:intern-jay", relation: "banned", object: "repo:patient-records" },
      { subject: "user:intern-jay", relation: "banned", object: "repo:pharmacy" },
    ],
  },
  {
    id: "tenant-edutech",
    name: "EduLearn — Online Education Platform",
    description: "EdTech startup: instructors, students, TAs with tiered repo access",
    tuples: [
      { subject: "user:prof-chen", relation: "admin", object: "org:edulearn" },
      { subject: "user:ta-maria", relation: "member", object: "org:edulearn" },
      { subject: "user:student-alex", relation: "member", object: "org:edulearn" },
      { subject: "user:student-ben", relation: "member", object: "org:edulearn" },
      { subject: "user:prof-chen", relation: "admin", object: "team:instructors" },
      { subject: "user:ta-maria", relation: "maintainer", object: "team:teaching-assistants" },
      { subject: "user:student-alex", relation: "member", object: "team:students" },
      { subject: "user:student-ben", relation: "member", object: "team:students" },
      { subject: "team:instructors#member", relation: "admin", object: "repo:course-content" },
      { subject: "team:teaching-assistants#member", relation: "maintainer", object: "repo:course-content" },
      { subject: "team:students#member", relation: "viewer", object: "repo:course-content" },
      { subject: "team:instructors#member", relation: "admin", object: "repo:gradebook" },
      { subject: "team:teaching-assistants#member", relation: "viewer", object: "repo:gradebook" },
      { subject: "user:student-ben", relation: "banned", object: "repo:gradebook" },
    ],
  },
  {
    id: "tenant-gamedev",
    name: "PixelForge — Game Studio",
    description: "Indie game studio: artists, devs, QA — strict separation of engine source vs assets",
    tuples: [
      { subject: "user:ceo-nina", relation: "admin", object: "org:pixelforge" },
      { subject: "user:lead-dev-kai", relation: "admin", object: "org:pixelforge" },
      { subject: "user:artist-zoe", relation: "member", object: "org:pixelforge" },
      { subject: "user:qa-rex", relation: "member", object: "org:pixelforge" },
      { subject: "user:lead-dev-kai", relation: "admin", object: "team:engine-devs" },
      { subject: "user:artist-zoe", relation: "member", object: "team:artists" },
      { subject: "user:qa-rex", relation: "admin", object: "team:qa" },
      { subject: "team:engine-devs#member", relation: "admin", object: "repo:engine-core" },
      { subject: "team:artists#member", relation: "admin", object: "repo:art-assets" },
      { subject: "team:engine-devs#member", relation: "viewer", object: "repo:art-assets" },
      { subject: "team:qa#member", relation: "viewer", object: "repo:engine-core" },
      { subject: "team:qa#member", relation: "viewer", object: "repo:art-assets" },
      { subject: "team:engine-devs#member", relation: "admin", object: "repo:ci-pipeline" },
    ],
  },
  {
    id: "tenant-logistics",
    name: "FastTrack — Logistics & Supply Chain",
    description: "Logistics company: drivers, dispatchers, managers — fleet and route data",
    tuples: [
      { subject: "user:mgr-diana", relation: "admin", object: "org:fasttrack" },
      { subject: "user:dispatcher-sam", relation: "member", object: "org:fasttrack" },
      { subject: "user:driver-leo", relation: "member", object: "org:fasttrack" },
      { subject: "user:driver-mia", relation: "member", object: "org:fasttrack" },
      { subject: "user:mgr-diana", relation: "admin", object: "team:management" },
      { subject: "user:dispatcher-sam", relation: "admin", object: "team:dispatch" },
      { subject: "user:driver-leo", relation: "member", object: "team:drivers" },
      { subject: "user:driver-mia", relation: "member", object: "team:drivers" },
      { subject: "team:management#member", relation: "admin", object: "repo:route-planner" },
      { subject: "team:dispatch#member", relation: "maintainer", object: "repo:route-planner" },
      { subject: "team:drivers#member", relation: "viewer", object: "repo:route-planner" },
      { subject: "team:management#member", relation: "admin", object: "repo:fleet-tracker" },
      { subject: "team:dispatch#member", relation: "viewer", object: "repo:fleet-tracker" },
    ],
  },
  {
    id: "tenant-media",
    name: "StreamVault — Media & Content",
    description: "Media company: editors, producers, distributors — content repo access by tier",
    tuples: [
      { subject: "user:exec-petra", relation: "admin", object: "org:streamvault" },
      { subject: "user:producer-dan", relation: "admin", object: "org:streamvault" },
      { subject: "user:editor-fiona", relation: "member", object: "org:streamvault" },
      { subject: "user:contractor-vik", relation: "member", object: "org:streamvault" },
      { subject: "user:producer-dan", relation: "admin", object: "team:production" },
      { subject: "user:editor-fiona", relation: "maintainer", object: "team:editorial" },
      { subject: "user:contractor-vik", relation: "member", object: "team:external" },
      { subject: "team:production#member", relation: "admin", object: "repo:raw-footage" },
      { subject: "team:editorial#member", relation: "maintainer", object: "repo:raw-footage" },
      { subject: "team:production#member", relation: "admin", object: "repo:published-content" },
      { subject: "team:editorial#member", relation: "maintainer", object: "repo:published-content" },
      { subject: "team:external#member", relation: "viewer", object: "repo:published-content" },
      { subject: "user:contractor-vik", relation: "banned", object: "repo:raw-footage" },
    ],
  },
  {
    id: "tenant-banking",
    name: "NovaCrest — Retail Banking",
    description: "Bank: tellers, loan officers, risk team, auditors — strict RBAC with deny overrides",
    tuples: [
      { subject: "user:cto-helen", relation: "admin", object: "org:novacrest" },
      { subject: "user:teller-omar", relation: "member", object: "org:novacrest" },
      { subject: "user:loan-officer-gita", relation: "member", object: "org:novacrest" },
      { subject: "user:auditor-jack", relation: "member", object: "org:novacrest" },
      { subject: "user:risk-analyst-ann", relation: "member", object: "org:novacrest" },
      { subject: "user:teller-omar", relation: "member", object: "team:tellers" },
      { subject: "user:loan-officer-gita", relation: "member", object: "team:loans" },
      { subject: "user:auditor-jack", relation: "admin", object: "team:audit" },
      { subject: "user:risk-analyst-ann", relation: "member", object: "team:risk" },
      { subject: "team:tellers#member", relation: "viewer", object: "repo:customer-accounts" },
      { subject: "team:loans#member", relation: "maintainer", object: "repo:customer-accounts" },
      { subject: "team:loans#member", relation: "admin", object: "repo:loan-origination" },
      { subject: "team:audit#member", relation: "viewer", object: "repo:customer-accounts" },
      { subject: "team:audit#member", relation: "viewer", object: "repo:loan-origination" },
      { subject: "team:risk#member", relation: "viewer", object: "repo:loan-origination" },
      { subject: "team:risk#member", relation: "admin", object: "repo:risk-models" },
      { subject: "user:teller-omar", relation: "banned", object: "repo:loan-origination" },
    ],
  },
];
