/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const access_diff: (a: number, b: number, c: number, d: number, e: number, f: bigint) => [number, number, number, number];
export const active_partition: () => [number, number, number, number];
export const approve_policy_draft: (a: number, b: number) => [number, number, number, number];
export const archive_policy_draft: (a: number, b: number) => [number, number, number, number];
export const check: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const create_analysis_schedule: (a: number, b: number) => [number, number, number, number];
export const create_policy_draft: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const delete_analysis_schedule: (a: number, b: number) => [number, number, number, number];
export const delete_relation: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const enforcement_trends: (a: number) => [number, number, number, number];
export const explain_v2: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const export_json: () => [number, number, number, number];
export const get_analysis_runs: (a: number) => [number, number, number, number];
export const get_enforcement_history_config: () => [number, number, number, number];
export const import_json: (a: number, b: number) => [number, number, number, number];
export const init_async: (a: number, b: number) => [number, number, number, number];
export const init_sync: (a: number, b: number, c: number) => [number, number, number, number];
export const list_analysis_schedules: () => [number, number, number, number];
export const list_by_object: (a: number, b: number) => [number, number, number, number];
export const list_by_subject: (a: number, b: number) => [number, number, number, number];
export const list_policy_drafts: (a: number, b: number) => [number, number, number, number];
export const list_policy_versions: () => [number, number, number, number];
export const publish_policy_draft: (a: number, b: number) => [number, number, number, number];
export const reject_policy_draft: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const rollback_policy: (a: number) => [number, number, number, number];
export const run_analysis_now: (a: number, b: number) => [number, number, number, number];
export const set_enforcement_history_config: (a: number, b: number) => [number, number, number, number];
export const set_partition: (a: number, b: number) => [number, number, number, number];
export const submit_policy_draft_for_review: (a: number, b: number) => [number, number, number, number];
export const subscribe: (a: number, b: number) => [number, number, number, number];
export const update_policy_draft: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const validate_policy_draft: (a: number, b: number) => [number, number, number, number];
export const who_can_access: (a: number, b: number, c: number, d: number, e: bigint, f: bigint, g: number) => [number, number, number, number];
export const write_relation: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
